services:
    proxyauth:
        container_name: proxyauth
        build: .
        user: "1000:1000"
        ports:
            - "8080:8080"
        ulimits:
            nofile:
                soft: 65536
                hard: 65536
        volumes:
            - ./config/config.json:/etc/proxyauth/config/config.json:rw
            - ./config/routes.yml:/etc/proxyauth/config/routes.yml:rw
