services:
    proxyauth:
        container_name: proxyauth
        build: .
        user: "1000:1000"
        ports:
            - "8080:8080"
        ulimits:
            nofile:
                soft: 65536
                hard: 65536
        volumes:
          - ./config:/etc/proxyauth/config:rw
