services:
    proxyauth:
        build: .
        user: "1000:1000"
        ulimits:
            nofile:
                soft: 65536
                hard: 65536
        volumes:
          - ./config:/etc/proxyauth/config:rw
          - proxyauth-db:/opt/proxyauth/db
        ports:
          - 8080:8080
volumes:
  proxyauth-db:
