services:
    proxyauth:
        container_name: proxyauth_beta
        build: .
        user: "1000:1000"
        ports:
            - "8080:8080"
        ulimits:
            nofile:
                soft: 65536
                hard: 65536
        volumes:
          - ./config:/etc/proxyauth/config:rw
          - proxyauth-db:/opt/proxyauth/db

volumes:
  proxyauth-db:
